[window.py]
  [test_same_id_after_cross_origin_navigation]
    expected: FAIL
